### ISSUE TITLE
iput of a file overwrites the content of file with its filename

### ISSUE THREAD

**Issue by chStaiger** [irods/irods_client_library_rirods#10]
We start reading in a text file:
```r
helloWorld = read.delim("helloWorld.txt", sep=" ")
```
Content of the file:

```
> helloWorld
[1] Hello  World.
<0 rows> (or 0-length row.names)
```
Now we store the file **helloWorld.txt** (not the variable) in iRODS:
```r
iput("helloWorld.txt")
ils()
                            logical_path        type
1           /bobZone/home/christine/test  collection
2            /bobZone/home/christine/foo data_object
3 /bobZone/home/christine/helloWorld.txt data_object
```

We rename our local file helloWorld.txt to helloWorld1.txt and download helloWorld.txt again from iRODS:
```r
iget("helloWorld.txt")
read.delim("helloWorld.txt", sep=" ")
[1] helloWorld.txt
<0 rows> (or 0-length row.names)
```

I can confirm that the `iput` is overwriting the content, since I get the same content of the file with the commands:
```
cstaiger@rirods:~$ iget helloWorld.txt
cstaiger@rirods:~$ cat helloWorld.txt
helloWorld.txt
```

**Comment by MartinSchobben** [comment]
If I am not mistaken this is because I forgot to add `txt` to a switch statement. However, csv and tsv should work. I will patch this soon.

**Comment by MartinSchobben** [comment]
PR #19 fixed this
