### ISSUE TITLE
Allow to rename data objects and collections in iget and iput when working with files

### ISSUE THREAD

**Issue by chStaiger** [irods/irods_client_library_rirods#11]
Assign a new file name when downloading data from iRODS and when uploading data to iRODS

Case for downloading. In my workspace  I already have 
```
> list.files()
[1] "helloWorld.txt"  "penguins.csv"   
```

In iRODS I also have a file `helloWorld.txt`:
```
> ils()
                            logical_path        type
1           /bobZone/home/christine/test  collection
...
4 /bobZone/home/christine/helloWorld.txt data_object
```
When I now try to download the file, I get:

```
> iget("helloWorld.txt")
Error: Local file aready exists. Set `overwrite = TRUE` to explicitely overwrite the object.
```

Is it possible to rewrite the call for get and  iput and get like this:
```
iget("helloWorld.txt", name="helloWorld1.txt", ... <all other parameter> )
iput("helloWorld.txt", name="helloWorld1.txt", ... <all other parameters>)
```

**Comment by MartinSchobben** [comment]
I am of the opinion that this should not be added to the function in argument, but rather leave this to the user, would go just do the following in R.

### R objects
```
baz <- foo
iput(foo)
```
### File
```
file.rename("foo.txt", "baz.txt")
iput("foo.txt")
```
