### ISSUE TITLE
proposal for iget and iput behavior

### ISSUE THREAD

**Issue by trel** [irods/irods_client_library_rirods#15]
I think `iput` and `iget` could be more consistent and mirror each other's behavior ...  with strong defaults...

`iput` should take an R variable and a target string for the name of the target data object in iRODS (with a default value of the name of the variable with an appended '.rds')

and reciprocally...

`iget` should take a string of the name of the absolute or relative logical path of the data object in iRODS and return an l-value of the content to an R variable

---

Hmmm, but what if `iput` or `iget` want to just transfer a file, rather than interacting with R variables?

```
# puts local variable's content into iRODS - without additional .rds extension
iput(x, "logical_path")

# puts a local file into iRODS
iput("local_file", "logical_path")
```
and

```
# gets iRODS data object, tries to put the content into local variable x (what does failure look like?)
iget("logical_path", x)  <-- more consistent
# OR
x <- iget("logical_path") <-- more R-ish?

# gets iRODS data object, saves to local file
iget("logical_path", "local_file")
```

**Comment by MartinSchobben** [comment]
I agree.

Basically, I think that `iput()` should be modeled after `saveRDS()` and `write.table()`, for R objects and files, respectively. That means:
```
# puts local variable's content into iRODS - without additional .rds extension
iput(x, "logical_path")

# puts a local file into iRODS
iput("local_file", "logical_path")
```
And, `iget()` should be modeled after `readRDS()` and `read.table()`, for R objects and files, respectively. That means:
```
x <- iget("logical_path") <-- more R-ish?
```
And, this also means that failure always precedes `<-`, so, I believe that should work fine in the current implementation.

This, however, leaves giving proper extensions to the responsibility of the user. This migh not be desired for R objects and the respective `.rds` extension.

**Comment by trel** [comment]
> failure always precedes `<-` 

On the `iget("logical_path")`... does that mean it will never be useful to get a non-data-frame data object from iRODS?  Like a ".jpg" or ".xlsx" or ".dcm"?

**Comment by MartinSchobben** [comment]
They can be, but they will be stored in the local directory, not dumped in the R environment. Otherwise, you have to build all that logic into `iget()`, which I do not find useful. Rather I would say leave it up to the user to deal with those formats. There are many R packages that can help them with converting those formats to R data structures.

**Comment by trel** [comment]
Right - I was talking about saving to a JPG to the local directory - just as a file transfer mechanism from iRODS...

Which is why I was suggesting, for consistency...
```
# gets iRODS data object, saves to local file
iget("logical_path", "local_file")
```

**Comment by MartinSchobben** [comment]
Oh yes, but that was already the default behavior.

**Comment by trel** [comment]
I think I'm still confused - might need a call to talk it out more.

**Comment by trel** [comment]
closing - for now - will open a new issue with any updates.
