### ISSUE TITLE
Should `icd()` behave like `setwd()` but on iRODS?

### ISSUE THREAD

**Issue by montesmariana** [irods/irods_client_library_rirods#24]
Currently, `icd()` (1) has no default value, although the documentation says so and (2) does not accept a trailing slash in path names.

The first point is consistent with the behavior of `setwd()` but not with the iCommands behavior of `icd` or the command-line behavior of `cd`, which defaults to the top-most level ('/zone/home/' for iRODS). That's what the documentation of `icd()` suggests, but, as the example below shows, `icd()` currently throws an error instead.

The second point is more concerning: based on the behavior of `setwd()`, `icd()` and `cd()`, a trailing slash should make no difference. Below it's shown that using a relative path (either "collection_name" or "..") or an absolute path (e.g. "/tempZone/home/rods") works well if there are no trailing slashes, but fails with a trailing slash. `ipwd()` doesn't catch the issue because it returns the absolute version of the provided path, but `ils()` shows that the contents are not correct.

``` r
library(rirods)
create_irods("http://localhost/irods-rest/0.9.3", "/tempZone/home", overwrite = TRUE)
iauth('rods', 'rods')
ipwd()
#> [1] "/tempZone/home/rods"
icd() # this fails because `dir` is not provided
#> Error in icd(): argument "dir" is missing, with no default
icd('.') # this brings us to where we already are
ipwd()
#> [1] "/tempZone/home/rods"
ils() # current content of top collection
#>                     logical_path        type
#> 1 /tempZone/home/rods/collection  collection
#> 2    /tempZone/home/rods/foo.rds data_object
icd('collection') # this brings us to 'collection' inside our pwd
ipwd()
#> [1] "/tempZone/home/rods/collection"
ils()
#>                                   logical_path       type
#> 1 /tempZone/home/rods/collection/subcollection collection
icd('../') # this fails
ipwd() # it's not obvious here because the right path is returned
#> [1] "/tempZone/home/rods/"
ils() # the contents are not correct: this is not the right path!
#> This collection does not contain any objects or collections.
icd('/tempZone/home/rods/') # absolute path is not the solution: trailing slash is the problem
ipwd()
#> [1] "/tempZone/home/rods/"
ils()
#> This collection does not contain any objects or collections.
icd('/tempZone/home/rods') # with no trailing slash, results are correct
ils()
#>                     logical_path        type
#> 1 /tempZone/home/rods/collection  collection
#> 2    /tempZone/home/rods/foo.rds data_object
icd('collection')
ils()
#>                                   logical_path       type
#> 1 /tempZone/home/rods/collection/subcollection collection
icd('..') # with no trailing slash, it works
ipwd()
#> [1] "/tempZone/home/rods"
ils()
#>                     logical_path        type
#> 1 /tempZone/home/rods/collection  collection
#> 2    /tempZone/home/rods/foo.rds data_object
```

<sup>Created on 2023-03-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'm leaving this here to report the problem, but I also offer to try to fix it if you agree that the trailing slash should be accepted (or, if it won't, then a message should be shown).

**Comment by trel** [comment]
I think a trailing slash should be allowed/ignored.
