### ISSUE TITLE
update to use the new iRODS HTTP API

### ISSUE THREAD

**Issue by trel** [irods/irods_client_library_rirods#41]
new HTTP API: https://github.com/irods/irods_client_http_api

---

Two options...

A) convert all the existing calls from using the REST API to the HTTP API
 - depends on the irods_demo being updated as well

OR

B) add the ability for this library to talk to the HTTP API, in addition to the REST API
 - add configuration option to select/target which API
 - every function has to learn how to hit both

It's not clear whether there will be any demand for B) once most people upgrade to the HTTP API (and iRODS 4.3.1+).

**Comment by montesmariana** [comment]
Depending on how much adaptation the lowest level functions need to be able to talk to either API, I would lean towards B as a way to make the package more flexibe to other future APIs.

**Comment by MartinSchobben** [comment]
I started with the first changes to HTTP API.  I opted now for option B.

The first larger design issue is whether we should duplicate all tests for both REST and HTTP. Alternatively we can define the API in the test setup file, as shown here:

https://github.com/MartinSchobben/irods_client_library_rirods/blob/7802fab833844fee0043b6e0cd36bd65baa347bf/tests/testthat/setup.R

This would mean that you always have to select which API you use to test against, which probably will be mostly HTTP in the future.

Any thoughts?

**Comment by MartinSchobben** [comment]
For now the changes (only authenticate so far) required little change in the code,  and backward compatibility can thus be assured. The question was more whether the old functionality should also still be as stringently tested as before. I presume not. So, then the focus shifts towards HTTP overall.

**Comment by trel** [comment]
Correct - REST project is deprecated and archived.   No need to continue testing against it as far as I can tell.
