### ISSUE TITLE
Make GitHub repo more discoverable.

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_library_rirods#47]
I guess it would be good for people to find the package if we add some tags; probably "r", “r-package”, and "rstats".

Read here about discoverability of packages: https://devguide.ropensci.org/maintenance_github_grooming.html

**Comment by trel** [comment]
This is done - please confirm.

**Comment by trel** [comment]
oh, and through some clicking... found this!   https://github.com/jspijker/ricmd

**Comment by MartinSchobben** [comment]
Yes, I know about it. The same person as I mentioned in the PR thread.
