### ISSUE TITLE
rirods 0.1.2 has no GitHub release

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_library_rirods#48]
But it has a CRAN release.

**Comment by trel** [comment]
Which SHA should be marked as 0.1.2?

**Comment by MartinSchobben** [comment]
c5703097502bfd74d011a55ed4c0f80224c4e86b

This one is closest to what is submitted to CRAN. But I should this time first merge with iRODS main before submitting to CRAN. I remember now that we had this discussion once before.

**Comment by trel** [comment]
Okay, so, I will continue to wait - as that commit is dated Nov 20, 2023.

**Comment by MartinSchobben** [comment]
I also mean the current CRAN version: https://cran.r-project.org/web/packages/rirods/index.html, released in November. Not version 0.2.0 which is currently a PR (#46).

**Comment by trel** [comment]
Oh!  Now I understand.   Will get that tagged/released.

**Comment by trel** [comment]
Done!   https://github.com/irods/irods_client_library_rirods/releases/tag/v0.1.2
