### ISSUE TITLE
allow non-standard evaluation for argument `x` of `iget()`

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_library_rirods#8]
Currently, argument `x` of `iget()` only allows character strings and not expressions. In the situation that one stores an R object first with `iput(foo)` it would be more logical to also retrieve the object with `iget(foo)` (and not `iget("foo")`). This means supplying an expression and thus non-standard evaluation (nse), similar like e.g. `subset(airquality, Temp > 80, select = c(Ozone, Temp))`.

Downside is that nse can make code less obvious to interpret and maintain.

In addition, the requirement of character strings for `iget()` is not documented currently.

**Comment by MartinSchobben** [comment]
not relevant anymore

**Comment by trel** [comment]
see conversation and commits for #15
