### ISSUE TITLE
Uploading larger R objects fails unexpected

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_library_rirods#9]
Uploading larger R objects fails unexpected.

``` r
library(rirods)
rirods:::local_create_irods() 
iauth("rods", "rods")
iput(iris)
#> Error in `httr2::req_perform()`:
#> ! Failed to parse error body with method defined in req_error()
#> Caused by error:
#> ! lexical error: invalid char in json text.
#>                                        Request exceeded maximum buffer
#>                      (right here) ------^

#> Backtrace:
#>      ▆
#>   1. ├─rirods::iput(iris)
#>   2. │ └─rirods:::irods_rest_call("stream", "PUT", args, verbose, x)
#>   3. │   └─httr2::req_perform(req)
#>   4. │     ├─httr2:::resp_abort(resp, error_body(req, resp))
#>   5. │     │ └─rlang::abort(...)
#>   6. │     │   └─rlang::is_formula(message, scoped = TRUE, lhs = FALSE)
#>   7. │     └─httr2:::error_body(req, resp)
#>   8. │       ├─rlang::try_fetch(...)
#>   9. │       │ ├─base::tryCatch(...)
#>  10. │       │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  11. │       │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  12. │       │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  13. │       │ └─base::withCallingHandlers(...)
#>  14. │       └─httr2:::req_policy_call(req, "error_body", list(resp), default = NULL)
#>  15. │         ├─rlang::exec(req$policies[[name]], !!!args)
#>  16. │         └─rirods (local) `<fn>`(`<httr2_rs>`)
#>  17. │           └─httr2::resp_body_json(resp, check_type = FALSE)
#>  18. │             └─jsonlite::fromJSON(text, simplifyVector = simplifyVector, ...)
#>  19. │               └─jsonlite:::parse_and_simplify(...)
#>  20. │                 └─jsonlite:::parseJSON(txt, bigint_as_char)
#>  21. │                   └─jsonlite:::parse_string(txt, bigint_as_char)
#>  22. └─base::.handleSimpleError(...)
#>  23.   └─rlang (local) h(simpleError(msg, call))
#>  24.     └─handlers[[1L]](cnd)
#>  25.       └─rlang::abort(...)
```

<sup>Created on 2022-11-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by trel** [comment]
how big is the maximum buffer?

can it be increased... should it be a parameter?

what is the downside to increasing such a value?

**Comment by MartinSchobben** [comment]
Should buffer size be defined in the header of the curl request? If so, then I can include another parameter or define a usefull value. I am actually also unsure how one knows what buffer size is needed and what's it for anyway.

**Comment by korydraughn** [comment]
It sounds like the `count` parameter is what you want.

It is specified as part of the URL just like `logical-path`. See https://github.com/irods/irods_client_rest_cpp#stream
```
&count=<integer>
```

The /stream endpoint is meant to be used like POSIX read/write functions. You must make multiple calls to stream large amounts of data. The `count` parameter tells the endpoint how many bytes are to be read or written.

As for the size of the buffer, larger values for `count` mean fewer network calls. Smaller values for `count` mean more network calls. Try starting with a count of 8192 bytes and increasing it to see what kind of performance you get. The value you land on can be the default. The user can then choose to override that if they feel it is too small or large.

**Comment by MartinSchobben** [comment]
I see. I did set it to 1000 by default, so I will change that but leave it accessible for the user.

**Comment by MartinSchobben** [comment]
I made an example mostly written in a bash script with only a piece of R that creates an 10,000 row-sized matrix. This mimics about what the R function does but I can't seem to fix `count` in such a way that this works without exceeding the buffer. 

```{bash}
#!/bin/sh

# get token
export SECRETS=$(echo -n rods:rods | base64)
export TOKEN=$(curl -X POST -H "Authorization: Basic ${SECRETS}" http://localhost/irods-rest/0.9.3/auth)

# R object
Rscript -e "foo <- matrix(1:10000); saveRDS(foo, 'foo.rds')"

# url encode with php
export LPATH=$( php -r "echo urlencode('/tempZone/home/rods/foo.rds');"; )

# create file
curl -X PUT -H "Authorization: ${TOKEN}" \
  -H "Accept-Encoding: gzip, deflate, br" \
  -d @foo.rds \
  "http://localhost/irods-rest/0.9.3/stream?logical-path=${LPATH}&offset=0&count=8192"

# delete file
rm foo.rds

```

**Comment by trel** [comment]
How big is 'foo.rds' on the disk?   That is the number that 'should' work for the `count=`.

**Comment by korydraughn** [comment]
> How big is 'foo.rds' on the disk? That is the number that 'should' work for the `count=`.

That is true if it is small. The REST API allocates a buffer of size `count` bytes. If `count` is too large, the server could throw a `std::bad_alloc` exception.

`offset` and `count` must be used to read/write large files.

**Comment by korydraughn** [comment]
That is correct.

The C++ REST API does not support parallel transfer yet, so the speed of a transfer will depend on the size of the file. That is a known issue and will be worked on in a future release of the API.

**Comment by MartinSchobben** [comment]
I am now able to upload larger object with chunking. You can see here that local and irods file sizes match:

``` r
library("rirods")
rirods:::local_create_irods()
iauth("rods", "rods")
# big object
foo <- matrix(1:100000)
# save locally
saveRDS(foo, "foo.rds")
# check size
file.size("foo.rds")
#> [1] 212424
# put in irods
iput(foo)
# check size on irods
ils(stat = TRUE)
#>                  logical_path status_information.last_write_time
#> 1 /tempZone/home/rods/foo.rds                         1670143173
#>   status_information.size        type
#> 1                  212424 data_object
```
But something goes wrong during the upload, and on closer inspection by looking at the raw vector, it seems like that the chunks in the front get overwritten with `00 00 00` bytes. Whereas the last chunk represents the source truthfully.

Any ideas? 

<sup>Created on 2022-12-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by korydraughn** [comment]
Ok, so when you say chunked, you're talking about manually sending parts of the file, not HTTP's chunked encoding. That's good.

I noticed you're passing `truncate=0`. Try changing it to `truncate=false` and seeing if it works.

**Comment by korydraughn** [comment]
We've made a tweak to the C++ REST API to allow larger HTTP requests. Before the change, the /stream endpoint for PUT was limited to about 4096 bytes (not good for uploads).

If that seems important to have for your talk, you can try building a package with that change. The PR is available at the following:
- https://github.com/irods/irods_client_rest_cpp/pull/175.

Generating a package can be accomplished using the Docker builder provided by the project. See the instructions at the following:
- https://github.com/irods/irods_client_rest_cpp#building-with-docker.

And here's instructions for running with Docker Compose.
- https://github.com/irods/irods_client_rest_cpp#starting-the-services-with-docker-compose.

**Comment by MartinSchobben** [comment]
oh my this works: `truncate=false`

**Comment by korydraughn** [comment]
We're going to change that in the next release to accept 0/1 instead of true/false.
- https://github.com/irods/irods_client_rest_cpp/issues/176
